In [6]:
import pandas as pd
Order_ID_dict={'1':'CA-2016-152156',
              '2':'CA-2016-152156',
              '3':'CA-2016-138688',
              '4':'US-2015-108966',
              '5':'US-2015-108966',
              '6':'CA-2014-115812',
              '7':'CA-2014-115812',
              '8':'CA-2014-115812',
              '9':'CA-2014-115812',
              '10':'CA-2014-115812',
              '11':'CA-2014-115812',
              '12':'CA-2014-115812',
              '13':'CA-2017-114412',
              '14':'CA-2016-161389',
              '15':'US-2015-118983',
              '16':'US-2015-118983',
              '17':'CA-2014-105893',
              '18':'CA-2014-167164',
              '19':'CA-2014-143336',
              '20':'CA-2014-143336',
              '21':'CA-2014-143336',
              '22':'CA-2016-137330',
              '23':'CA-2016-137330',
              '24':'US-2017-156909',
              '25':'CA-2015-106320',
              '26':'CA-2016-121755',
              '27':'CA-2016-121755',
              '28':'US-2015-150630',
              '29':'US-2015-150630',
              '30':'US-2015-150630',
              '31':'US-2015-150630',
              '32':'US-2015-150630',
              '33':'US-2015-150630',
              '34':'US-2015-150630',
              '35':'CA-2017-107727',
              '36':'CA-2016-117590',
              '37':'CA-2016-117590',
              '38':'CA-2015-117415',
              '39':'CA-2015-117415',
              '40':'CA-2015-117415',
              '41':'CA-2015-117415',
              '42':'CA-2017-120999',
              '43':'CA-2016-101343',
              '44':'CA-2017-139619',
              '45':'CA-2016-118255',
              '46':'CA-2016-118255',
              '47':'CA-2014-146703',
              '48':'CA-2016-169194',
              '49':'CA-2016-169194',
              '50':'CA-2015-115742',
              '51':'CA-2015-115742',
              '52':'CA-2015-115742',
              '53':'CA-2015-115742',
              '54':'CA-2016-105816',
              '55':'CA-2016-105816',
              '56':'CA-2016-111682',
              '57':'CA-2016-111682',
              '58':'CA-2016-111682',
              '59':'CA-2016-111682',
              '60':'CA-2016-111682',
              '61':'CA-2016-111682',
              '62':'CA-2016-111682',
              '63':'CA-2015-135545',
              '64':'CA-2015-135545',
              '65':'CA-2015-135545',
              '66':'CA-2015-135545',
              '67':'US-2015-164175',
              '68':'CA-2014-106376',
              '69':'CA-2014-106376',
              '70':'CA-2016-119823',
              '71':'CA-2016-106075',
              '72':'CA-2017-114440',
              '73':'US-2015-134026',
              '74':'US-2015-134026',
              '75':'US-2015-134026',
              '76':'US-2017-118038',
              '77':'US-2017-118038',
              '78':'US-2017-118038',
              '79':'US-2014-147606',
              '80':'CA-2016-127208',
              '81':'CA-2016-127208',
              '82':'CA-2014-139451',
              '83':'CA-2014-139451',
              '84':'CA-2015-149734',
              '85':'US-2017-119662',
              '86':'CA-2017-140088',
              '87':'CA-2017-140088',
              '88':'CA-2017-140088',
              '89':'CA-2016-159695',
              '90':'CA-2016-109806',
              '91':'CA-2016-109806',
              '92':'CA-2016-109806',
              '93':'CA-2015-149587',
              '94':'CA-2015-149587',
              '95':'CA-2015-149587',
              '96':'US-2017-109484',
              '97':'CA-2017-161018',
              '98':'CA-2017-157833',
              '99':'CA-2016-149223',
              '100':'CA-2016-158568'}
print(type(Order_ID_dict))
Order_ID=pd.Series(Order_ID_dict)
Order_ID

<class 'dict'>

1      CA-2016-152156
2      CA-2016-152156
3      CA-2016-138688
4      US-2015-108966
5      US-2015-108966
            ...
96     US-2017-109484
97     CA-2017-161018
98     CA-2017-157833
99     CA-2016-149223
100    CA-2016-158568
Length: 100, dtype: object

In [7]:
Order_Date_dict={'1':'2016.11.08',
              '2':'2016.11.08',
              '3':'2016.06.12',
              '4':'2015.10.11',
              '5':'2015.10.11',
              '6':'2014.06.09',
              '7':'2014.06.09',
              '8':'2014.06.09',
              '9':'2014.06.09',
              '10':'2014.06.09',
              '11':'2014.06.09',
              '12':'2014.06.09',
              '13':'2017.04.15',
              '14':'2016.12.05',
              '15':'2015.11.22',
              '16':'2015.11.22',
              '17':'2014.11.11',
              '18':'2014.05.13',
              '19':'2014.08.27',
              '20':'2014.08.27',
              '21':'2014.08.27',
              '22':'2016.12.09',
              '23':'2016.12.09',
              '24':'2017.07.16',
              '25':'2015.09.25',
              '26':'2016.01.16',
              '27':'2016.01.16',
              '28':'2015.09.17',
              '29':'2015.09.17',
              '30':'2015.09.17',
              '31':'2015.09.17',
              '32':'2015.09.17',
              '33':'2015.09.17',
              '34':'2015.09.17',
              '35':'2017.10.19',
              '36':'2016.12.08',
              '37':'2016.12.08',
              '38':'2015.12.27',
              '39':'2015.12.27',
              '40':'2015.12.27',
              '41':'2015.12.27',
              '42':'2017.09.10',
              '43':'2016.07.17',
              '44':'2017.09.19',
              '45':'2016.03.11',
              '46':'2016.03.11',
              '47':'2014.10.20',
              '48':'2016.06.20',
              '49':'2016.06.20',
              '50':'2015.04.18',
              '51':'2015.04.18',
              '52':'2015.04.18',
              '53':'2015.04.18',
              '54':'2016.12.11',
              '55':'2016.12.11',
              '56':'2016.06.17',
              '57':'2016.06.17',
              '58':'2016.06.17',
              '59':'2016.06.17',
              '60':'2016.06.17',
              '61':'2016.06.17',
              '62':'2016.06.17',
              '63':'2015.11.24',
              '64':'2015.11.24',
              '65':'2015.11.24',
              '66':'2015.11.24',
              '67':'2015.04.30',
              '68':'2014.12.05',
              '69':'2014.12.05',
              '70':'2016.06.04',
              '71':'2016.09.18',
              '72':'2017.09.14',
              '73':'2015.04.26',
              '74':'2015.04.26',
              '75':'2015.04.26',
              '76':'2017.12.09',
              '77':'2017.12.09',
              '78':'2017.12.09',
              '79':'2014.11.26',
              '80':'2016.06.12',
              '81':'2016.06.12',
              '82':'2014.10.12',
              '83':'2014.10.12',
              '84':'2015.09.03',
              '85':'2017.11.13',
              '86':'2017.05.28',
              '87':'2017.10.26',
              '88':'2017.10.26',
              '89':'2016.04.05',
              '90':'2016.09.17',
              '91':'2016.09.17',
              '92':'2016.09.17',
              '93':'2015.01.31',
              '94':'2015.01.31',
              '95':'2015.01.31',
              '96':'2017.11.06',
              '97':'2017.11.09',
              '98':'2017.06.17',
              '99':'2016.09.06',
              '100':'2016.08.29'}
print(type(Order_Date_dict))
Order_Date=pd.Series(Order_Date_dict)
Order_Date

<class 'dict'>

1      2016.11.08
2      2016.11.08
3      2016.06.12
4      2015.10.11
5      2015.10.11
          ...
96     2017.11.06
97     2017.11.09
98     2017.06.17
99     2016.09.06
100    2016.08.29
Length: 100, dtype: object

In [10]:
Customer_ID_dict={'1':'EB-13930',
              '2':'EB-13930',
              '3':'MO-17950',
              '4':'JO-15550',
              '5':'JO-15550',
              '6':'RH-19600',
              '7':'RH-19600',
              '8':'RH-19600',
              '9':'RH-19600',
              '10':'RH-19600',
              '11':'RH-19600',
              '12':'RH-19600',
              '13':'GB-14530',
              '14':'PW-19030',
              '15':'RB-19570',
              '16':'RB-19570',
              '17':'JS-15940',
              '18':'SB-20170',
              '19':'HL-15040',
              '20':'HL-15040',
              '21':'HL-15040',
              '22':'DK-13225',
              '23':'DK-13225',
              '24':'CV-12805',
              '25':'NS-18640',
              '26':'AF-10885',
              '27':'AF-10885',
              '28':'JK-15625',
              '29':'JK-15625',
              '30':'JK-15625',
              '31':'JK-15625',
              '32':'JK-15625',
              '33':'JK-15625',
              '34':'JK-15625',
              '35':'BC-11125',
              '36':'JS-15595',
              '37':'JS-15595',
              '38':'CS-12355',
              '39':'CS-12355',
              '40':'CS-12355',
              '41':'CS-12355',
              '42':'JK-15205',
              '43':'SC-20695',
              '44':'JD-15895',
              '45':'CC-12475',
              '46':'CC-12475',
              '47':'PM-19135',
              '48':'CR-12580',
              '49':'CR-12580',
              '50':'TB-21400',
              '51':'TB-21400',
              '52':'TB-21400',
              '53':'TB-21400',
              '54':'SR-20740',
              '55':'SR-20740',
              '56':'BB-10990',
              '57':'BB-10990',
              '58':'BB-10990',
              '59':'BB-10990',
              '60':'BB-10990',
              '61':'BB-10990',
              '62':'BB-10990',
              '63':'EB-13870',
              '64':'EB-13870',
              '65':'EB-13870',
              '66':'EB-13870',
              '67':'QJ-19255',
              '68':'RC-19825',
              '69':'RC-19825',
              '70':'RE-19450',
              '71':'RB-19645',
              '72':'DL-13315',
              '73':'JL-15130',
              '74':'JL-15130',
              '75':'JL-15130',
              '76':'BO-11425',
              '77':'BO-11425',
              '78':'BO-11425',
              '79':'CL-12565',
              '80':'LM-17065',
              '81':'LM-17065',
              '82':'JM-15535',
              '83':'JM-15535',
              '84':'RP-19855',
              '85':'AG-10525',
              '86':'GH-14410',
              '87':'TS-21205',
              '88':'TS-21205',
              '89':'AF-10885',
              '90':'FM-14380',
              '91':'FM-14380',
              '92':'FM-14380',
              '93':'NS-18640',
              '94':'NS-18640',
              '95':'NS-18640',
              '96':'JR-15700',
              '97':'AJ-10945',
              '98':'BM-11575',
              '99':'CV-12805',
              '100':'DK-12835'}
print(type(Customer_ID_dict))
Customer_ID=pd.Series(Customer_ID_dict)
Customer_ID

<class 'dict'>

1      EB-13930
2      EB-13930
3      MO-17950
4      JO-15550
5      JO-15550
         ...
96     JR-15700
97     AJ-10945
98     BM-11575
99     CV-12805
100    DK-12835
Length: 100, dtype: object

In [12]:
Segment_dict={'1':'Хувь хүн',
              '2':'Хувь хүн',
              '3':'Байгууллага',
              '4':'Хувь хүн',
              '5':'Хувь хүн',
              '6':'Хувь хүн',
              '7':'Хувь хүн',
              '8':'Хувь хүн',
              '9':'Хувь хүн',
              '10':'Хувь хүн',
              '11':'Хувь хүн',
              '12':'Хувь хүн',
              '13':'Хувь хүн',
              '14':'Хувь хүн',
              '15':'Гишүүн',
              '16':'Гишүүн',
              '17':'Хувь хүн',
              '18':'Хувь хүн',
              '19':'Хувь хүн',
              '20':'Хувь хүн',
              '21':'Хувь хүн',
              '22':'Байгууллага',
              '23':'Байгууллага',
              '24':'Хувь хүн',
              '25':'Хувь хүн',
              '26':'Хувь хүн',
              '27':'Хувь хүн',
              '28':'Хувь хүн',
              '29':'Хувь хүн',
              '30':'Хувь хүн',
              '31':'Хувь хүн',
              '32':'Хувь хүн',
              '33':'Хувь хүн',
              '34':'Хувь хүн',
              '35':'Гишүүн',
              '36':'Байгууллага',
              '37':'Байгууллага',
              '38':'Гишүүн',
              '39':'Гишүүн',
              '40':'Гишүүн',
              '41':'Гишүүн',
              '42':'Байгууллага',
              '43':'Байгууллага',
              '44':'Байгууллага',
              '45':'Байгууллага',
              '46':'Байгууллага',
              '47':'Хувь хүн',
              '48':'Хувь хүн',
              '49':'Хувь хүн',
              '50':'Хувь хүн',
              '51':'Хувь хүн',
              '52':'Хувь хүн',
              '53':'Хувь хүн',
              '54':'Байгууллага',
              '55':'Байгууллага',
              '56':'Хувь хүн',
              '57':'Хувь хүн',
              '58':'Хувь хүн',
              '59':'Хувь хүн',
              '60':'Хувь хүн',
              '61':'Хувь хүн',
              '62':'Хувь хүн',
              '63':'Хувь хүн',
              '64':'Хувь хүн',
              '65':'Хувь хүн',
              '66':'Хувь хүн',
              '67':'Гишүүн',
              '68':'Байгууллага',
              '69':'Байгууллага',
              '70':'Хувь хүн',
              '71':'Хувь хүн',
              '72':'Хувь хүн',
              '73':'Хувь хүн',
              '74':'Хувь хүн',
              '75':'Хувь хүн',
              '76':'Байгууллага',
              '77':'Байгууллага',
              '78':'Байгууллага',
              '79':'Хувь хүн',
              '80':'Байгууллага',
              '81':'Байгууллага',
              '82':'Хувь хүн',
              '83':'Хувь хүн',
              '84':'Байгууллага',
              '85':'Гишүүн',
              '86':'Хувь хүн',
              '87':'Хувь хүн',
              '88':'Хувь хүн',
              '89':'Гишүүн',
              '90':'Байгууллага',
              '91':'Байгууллага',
              '92':'Байгууллага',
              '93':'Хувь хүн',
              '94':'Хувь хүн',
              '95':'Хувь хүн',
              '96':'Гишүүн',
              '97':'Гишүүн',
              '98':'Хувь хүн',
              '99':'Байгууллага',
              '100':'Гишүүн'}
print(type(Segment_dict))
Segment=pd.Series(Segment_dict)
Segment

<class 'dict'>

1         Хувь хүн
2         Хувь хүн
3      Байгууллага
4         Хувь хүн
5         Хувь хүн
          ...
96          Гишүүн
97          Гишүүн
98        Хувь хүн
99     Байгууллага
100         Гишүүн
Length: 100, dtype: object

In [13]:
Region_dict={'1':'Баянзүрх',
              '2':'Баянзүрх',
              '3':'Хан-Уул',
              '4':'Баянзүрх',
              '5':'Баянзүрх',
              '6':'Хан-Уул',
              '7':'Хан-Уул',
              '8':'Хан-Уул',
              '9':'Хан-Уул',
              '10':'Хан-Уул',
              '11':'Хан-Уул',
              '12':'Хан-Уул',
              '13':'Баянзүрх',
              '14':'Хан-Уул',
              '15':'Чингэлтэй',
              '16':'Чингэлтэй',
              '17':'Чингэлтэй',
              '18':'Хан-Уул',
              '19':'Хан-Уул',
              '20':'Хан-Уул',
              '21':'Хан-Уул',
              '22':'Чингэлтэй',
              '23':'Чингэлтэй',
              '24':'Сүхбаатар',
              '25':'Хан-Уул',
              '26':'Хан-Уул',
              '27':'Хан-Уул',
              '28':'Сүхбаатар',
              '29':'Сүхбаатар',
              '30':'Сүхбаатар',
              '31':'Сүхбаатар',
              '32':'Сүхбаатар',
              '33':'Сүхбаатар',
              '34':'Сүхбаатар',
              '35':'Чингэлтэй',
              '36':'Чингэлтэй',
              '37':'Чингэлтэй',
              '38':'Чингэлтэй',
              '39':'Чингэлтэй',
              '40':'Чингэлтэй',
              '41':'Чингэлтэй',
              '42':'Чингэлтэй',
              '43':'Хан-Уул',
              '44':'Баянзүрх',
              '45':'Чингэлтэй',
              '46':'Чингэлтэй',
              '47':'Чингэлтэй',
              '48':'Сүхбаатар',
              '49':'Сүхбаатар',
              '50':'Чингэлтэй',
              '51':'Чингэлтэй',
              '52':'Чингэлтэй',
              '53':'Чингэлтэй',
              '54':'Сүхбаатар',
              '55':'Сүхбаатар',
              '56':'Сүхбаатар',
              '57':'Сүхбаатар',
              '58':'Сүхбаатар',
              '59':'Сүхбаатар',
              '60':'Сүхбаатар',
              '61':'Сүхбаатар',
              '62':'Сүхбаатар',
              '63':'Хан-Уул',
              '64':'Хан-Уул',
              '65':'Хан-Уул',
              '66':'Хан-Уул',
              '67':'Чингэлтэй',
              '68':'Хан-Уул',
              '69':'Хан-Уул',
              '70':'Баянзүрх',
              '71':'Сүхбаатар',
              '72':'Чингэлтэй',
              '73':'Баянзүрх',
              '74':'Баянзүрх',
              '75':'Баянзүрх',
              '76':'Чингэлтэй',
              '77':'Чингэлтэй',
              '78':'Чингэлтэй',
              '79':'Чингэлтэй',
              '80':'Баянзүрх',
              '81':'Баянзүрх',
              '82':'Хан-Уул',
              '83':'Хан-Уул',
              '84':'Баянзүрх',
              '85':'Чингэлтэй',
              '86':'Баянзүрх',
              '87':'Чингэлтэй',
              '88':'Чингэлтэй',
              '89':'Чингэлтэй',
              '90':'Хан-Уул',
              '91':'Хан-Уул',
              '92':'Хан-Уул',
              '93':'Чингэлтэй',
              '94':'Чингэлтэй',
              '95':'Чингэлтэй',
              '96':'Хан-Уул',
              '97':'Сүхбаатар',
              '98':'Хан-Уул',
              '99':'Чингэлтэй',
              '100':'Чингэлтэй'}
print(type(Region_dict))
Region=pd.Series(Region_dict)
Region

<class 'dict'>

1       Баянзүрх
2       Баянзүрх
3        Хан-Уул
4       Баянзүрх
5       Баянзүрх
         ...
96       Хан-Уул
97     Сүхбаатар
98       Хан-Уул
99     Чингэлтэй
100    Чингэлтэй
Length: 100, dtype: object

In [14]:
Category_dict={'1':'Чихэр, печенье',
              '2':'OO ийн цаас, сальфетка',
              '3':'Чихэр, печенье',
              '4':'Хиам бууз',
              '5':'Ундаа ус',
              '6':'Жимс ногоо',
              '7':'Гурил будаа',
              '8':'Бичиг хэрэг',
              '9':'OO ийн цаас, сальфетка',
              '10':'Ундаа ус',
              '11':'OO ийн цаас, сальфетка',
              '12':'Ундаа ус',
              '13':'Архи пиво',
              '14':'Талх, нарийн боов',
              '15':'Ундаа ус',
              '16':'Ундаа ус',
              '17':'Саван бок',
              '18':'Зайрмаг',
              '19':'Бэлэн гоймон',
              '20':'Чихэр, печенье',
              '21':'Ундаа ус',
              '22':'OO ийн цаас, сальфетка',
              '23':'Хиам бууз',
              '24':'Зайрмаг',
              '25':'Гэр ахуй',
              '26':'Набор, шоколад, бохь',
              '27':'Чихэр, печенье',
              '28':'Гэр ахуй',
              '29':'Гурил будаа',
              '30':'Бэлэн гоймон',
              '31':'Ундаа ус',
              '32':'Жимс ногоо',
              '33':'Ундаа ус',
              '34':'Набор, шоколад, бохь',
              '35':'УНДАА УС',
              '36':'Самар чипс',
              '37':'Зайрмаг',
              '38':'ОО сойз',
              '39':'Гурил будаа',
              '40':'Архи пиво',
              '41':'Амтлагч',
              '42':'Гурил будаа',
              '43':'Чихэр, печенье',
              '44':'Ундаа ус',
              '45':'Ундаа ус',
              '46':'Саван бок',
              '47':'Бэлэн гоймон',
              '48':'Гурил будаа',
              '49':'Амтлагч',
              '50':'OO ийн цаас, сальфетка',
              '51':'Гурил будаа',
              '52':'Ундаа ус',
              '53':'Ундаа ус',
              '54':'Жимс ногоо',
              '55':'Амтлагч',
              '56':'OO ийн цаас, сальфетка',
              '57':'Самар чипс',
              '58':'Хиам бууз',
              '59':'OO ийн цаас, сальфетка',
              '60':'Лаазалсан бүтээгдэхүүн, ургамлын тос',
              '61':'Чихэр, печенье',
              '62':'Гоо сайхан',
              '63':'Саван бок',
              '64':'Чихэр, печенье',
              '65':'Гоо сайхан',
              '66':'Чихэр, печенье',
              '67':'Архи пиво',
              '68':'Архи пиво',
              '69':'Ундаа ус',
              '70':'Амтлагч',
              '71':'Гурил будаа',
              '72':'Самар чипс',
              '73':'Ундаа ус',
              '74':'Лаазалсан бүтээгдэхүүн, ургамлын тос',
              '75':'Гэр ахуй',
              '76':'Амтлагч',
              '77':'Жимс ногоо',
              '78':'Жимс ногоо',
              '79':'Чихэр, печенье',
              '80':'Самар чипс',
              '81':'Гэр ахуй',
              '82':'Ундаа ус',
              '83':'Лаазалсан бүтээгдэхүүн, ургамлын тос',
              '84':'Ундаа ус',
              '85':'Чихэр, печенье',
              '86':'Ундаа ус',
              '87':'Архи пиво',
              '88':'Лаазалсан бүтээгдэхүүн, ургамлын тос',
              '89':'Лаазалсан бүтээгдэхүүн, ургамлын тос',
              '90':'Чихэр, печенье',
              '91':'Гэр ахуй',
              '92':'Бэлэн гоймон',
              '93':'Чихэр, печенье',
              '94':'Архи пиво',
              '95':'Зайрмаг',
              '96':'Компот варенье, хүүхдийн тэжээл',
              '97':'Самар чипс',
              '98':'Набор, шоколад, бохь',
              '99':'Архи пиво',
              '100':'Бэлэн гоймон'}
print(type(Category_dict))
Category=pd.Series(Category_dict)
Category

<class 'dict'>

1                       Чихэр, печенье
2               OO ийн цаас, сальфетка
3                       Чихэр, печенье
4                            Хиам бууз
5                             Ундаа ус
                    ...
96     Компот варенье, хүүхдийн тэжээл
97                          Самар чипс
98                Набор, шоколад, бохь
99                           Архи пиво
100                       Бэлэн гоймон
Length: 100, dtype: object

In [15]:
Product_Name_dict={'1':'Shokolinsen 250 гр',
              '2':'Хэрэглээ 00ийн цаас',
              '3':'Алимтай жигнэмэг 230 гр',
              '4':'Золотой янта 500 гр',
              '5':'Punch 450 мл',
              '6':'Помидор том',
              '7':'Слава хивэг 400 гр',
              '8':'Үзгэн бал арилгадаг',
              '9':'Lady 20 ш',
              '10':'370 Жүүс 370 мл',
              '11':'Саль ариун 30 ш',
              '12':'Pysio 300 мл',
              '13':'A vodka 0.5',
              '14':'Өгөөж танзуур',
              '15':'Vita жимстэй ус 510 мл',
              '16':'Алое шилтэй 180 мл',
              '17':'Power 400 g',
              '18':'Пломбир на сливках 80 гр савтай',
              '19':'Удон гоймон ууттай',
              '20':'M&M 45 гр',
              '21':'Витафит ус 500 мл',
              '22':'Памперс №4',
              '23':'Solpro майонез 3 л 67 %',
              '24':'Магнат 80 гр',
              '25':'Хувцасны өлгүүр 5 ш алаг',
              '26':'Шингэн чихэр',
              '27':'Akuku резин 90 гр',
              '28':'Сахлын татуурга Gilette',
              '29':'Русский сахар 250 гр',
              '30':'Бэлэн гоймон төмстэй',
              '31':'Хүслийн ундаа 500 мл',
              '32':'Помидор том',
              '33':'Arizona лаазтай 680 мл',
              '34':'Jacobs кофе',
              '35':'Өглөө сүү',
              '36':'Амт чипс 55 гр',
              '37':'Эгоист 65 гр',
              '38':'Colgate total 100 гр',
              '39':'Слава гурвалжин будаа 650 гр',
              '40':'Хараа 0.75 цэвэр',
              '41':'Вигора 200 гр',
              '42':'Давс 1 кг',
              '43':'Mini cracker 350 гр',
              '44':'Arizona лаазтай 680 мл',
              '45':'Тоник лаазтай 330 мл',
              '46':'Tide 450 гр авто',
              '47':'Paldo king noodle 110 гр',
              '48':'Цесна 25 кг',
              '49':'Appetita плова',
              '50':'Саль ариун 100 ш',
              '51':'Слава каш 1 кг',
              '52':'Моя семъя 1 л',
              '53':'Зуун наст 1.25 мл',
              '54':'Мандарин',
              '55':'Appetita будаатай хуурга',
              '56':'Цэвэрхэн 00ийн цаас',
              '57':'Siesta үзэм 200 гр',
              '58':'Махеевь салатны 400 мл',
              '59':'Selpak 2 хайрцаг',
              '60':'Oleina тос 1 л',
              '61':'Чихэр кг Кокос 400 гр',
              '62':'Nivea тос 50 мл',
              '63':'Омо 100 гр',
              '64':'Өгөөж вафли',
              '65':'Head & Shoulders 400 мл',
              '66':'Жимстэй чокопай 6 ш',
              '67':'Соёолж 2.5 л',
              '68':'Тэргүүн 0.5',
              '69':'Витсамо ус 500 мл',
              '70':'Дашида 50 гр',
              '71':'Заантай будаа 5 кг',
              '72':'Lays чипс 80 гр',
              '73':'Алое шилтэй 180 мл',
              '74':'Хавиргатай рагу 454 гр',
              '75':'Хутга 1 ш',
              '76':'Appetita будаатай хуурга',
              '77':'Нандин чавга 250 гр',
              '78':'Чинжүү',
              '79':'Чихэр кг Конфет Кино 400 гр',
              '80':'Cocoro 100 гр',
              '81':'3н өнгийн алчуур',
              '82':'Оргилуун ус жимстэй 500 мл',
              '83':'Видан зөгийн бал',
              '84':'Сор жүүс 200 мл',
              '85':'Гурвалжин шоко 22 гр',
              '86':'Гоё тетра 1 л',
              '87':'Хараа 0.75 цэвэр',
              '88':'Шпрот урт татдаг 190 гр',
              '89':'Bagro хүрэн манжингийн салат 500 мл',
              '90':'Цагаан самар 50 гр',
              '91':'Махны мод дугуй',
              '92':'Биг ланч 110 гр савтай',
              '93':'Custard 6 ш',
              '94':'Алтантүрүү 0.5',
              '95':'Фифти фифти 180 гр',
              '96':'Hainich нухаш',
              '97':'Lays чипс 80 гр',
              '98':'Монстров 23 гр',
              '99':'Арвай 0.100',
              '100':'Тэйсти гоймон 110 гр'}
print(type(Product_Name_dict))
Product_Name=pd.Series(Product_Name_dict)
Product_Name

<class 'dict'>

1           Shokolinsen 250 гр
2          Хэрэглээ 00ийн цаас
3      Алимтай жигнэмэг 230 гр
4          Золотой янта 500 гр
5                 Punch 450 мл
                ...
96               Hainich нухаш
97             Lays чипс 80 гр
98              Монстров 23 гр
99                 Арвай 0.100
100       Тэйсти гоймон 110 гр
Length: 100, dtype: object

In [16]:
Price_dict={'1':'3300',
              '2':'500',
              '3':'3100',
              '4':'2800',
              '5':'1150',
              '6':'4000',
              '7':'750',
              '8':'2500',
              '9':'2200',
              '10':'850',
              '11':'2200',
              '12':'1700',
              '13':'9000',
              '14':'3000',
              '15':'1050',
              '16':'1100',
              '17':'1600',
              '18':'1200',
              '19':'1200',
              '20':'1000',
              '21':'450',
              '22':'1000',
              '23':'7700',
              '24':'2500',
              '25':'2500',
              '26':'2100',
              '27':'1500',
              '28':'550',
              '29':'1100',
              '30':'1200',
              '31':'1050',
              '32':'4000',
              '33':'2500',
              '34':'240',
              '35':'2600',
              '36':'1300',
              '37':'900',
              '38':'4400',
              '39':'2100',
              '40':'11500',
              '41':'1500',
              '42':'200',
              '43':'3500',
              '44':'2500',
              '45':'1250',
              '46':'4100',
              '47':'2200',
              '48':'45000',
              '49':'450',
              '50':'1400',
              '51':'2000',
              '52':'3200',
              '53':'1900',
              '54':'4500',
              '55':'350',
              '56':'400',
              '57':'2700',
              '58':'1700',
              '59':'4800',
              '60':'4200',
              '61':'5500',
              '62':'3300',
              '63':'900',
              '64':'1950',
              '65':'12000',
              '66':'2300',
              '67':'5700',
              '68':'7600',
              '69':'500',
              '70':'800',
              '71':'13200',
              '72':'2300',
              '73':'1100',
              '74':'3400',
              '75':'3000',
              '76':'350',
              '77':'2000',
              '78':'4000',
              '79':'3000',
              '80':'2300',
              '81':'1100',
              '82':'1050',
              '83':'3300',
              '84':'500',
              '85':'600',
              '86':'1600',
              '87':'11500',
              '88':'3500',
              '89':'2200',
              '90':'500',
              '91':'13000',
              '92':'2300',
              '93':'2300',
              '94':'12500',
              '95':'2750',
              '96':'3300',
              '97':'2300',
              '98':'500',
              '99':'2000',
              '100':'1800'}
print(type(Price_dict))
Price=pd.Series(Price_dict)
Price

<class 'dict'>

1      3300
2       500
3      3100
4      2800
5      1150
       ...
96     3300
97     2300
98      500
99     2000
100    1800
Length: 100, dtype: object

In [17]:
Quantity_dict={'1':'2',
              '2':'3',
              '3':'2',
              '4':'5',
              '5':'2',
              '6':'7',
              '7':'4',
              '8':'6',
              '9':'3',
              '10':'5',
              '11':'9',
              '12':'4',
              '13':'3',
              '14':'3',
              '15':'5',
              '16':'3',
              '17':'6',
              '18':'2',
              '19':'2',
              '20':'3',
              '21':'4',
              '22':'7',
              '23':'7',
              '24':'2',
              '25':'3',
              '26':'2',
              '27':'3',
              '28':'7',
              '29':'2',
              '30':'3',
              '31':'2',
              '32':'6',
              '33':'6',
              '34':'2',
              '35':'3',
              '36':'7',
              '37':'5',
              '38':'9',
              '39':'3',
              '40':'3',
              '41':'4',
              '42':'4',
              '43':'2',
              '44':'2',
              '45':'2',
              '46':'2',
              '47':'4',
              '48':'3',
              '49':'2',
              '50':'6',
              '51':'6',
              '52':'2',
              '53':'1',
              '54':'7',
              '55':'5',
              '56':'6',
              '57':'5',
              '58':'5',
              '59':'2',
              '60':'2',
              '61':'4',
              '62':'1',
              '63':'2',
              '64':'6',
              '65':'3',
              '66':'4',
              '67':'5',
              '68':'8',
              '69':'4',
              '70':'2',
              '71':'1',
              '72':'3',
              '73':'8',
              '74':'2',
              '75':'1',
              '76':'3',
              '77':'3',
              '78':'3',
              '79':'5',
              '80':'1',
              '81':'3',
              '82':'5',
              '83':'1',
              '84':'7',
              '85':'3',
              '86':'2',
              '87':'1',
              '88':'2',
              '89':'7',
              '90':'3',
              '91':'2',
              '92':'1',
              '93':'2',
              '94':'3',
              '95':'2',
              '96':'1',
              '97':'7',
              '98':'3',
              '99':'6',
              '100':'2'}
print(type(Quantity_dict))
Quantity=pd.Series(Quantity_dict)
Quantity

<class 'dict'>

1      2
2      3
3      2
4      5
5      2
      ..
96     1
97     7
98     3
99     6
100    2
Length: 100, dtype: object

In [18]:
Discount_dict={'1':'0',
              '2':'0',
              '3':'0',
              '4':'0',
              '5':'0',
              '6':'0',
              '7':'0',
              '8':'0',
              '9':'0',
              '10':'0',
              '11':'0',
              '12':'0',
              '13':'0',
              '14':'0',
              '15':'0.03',
              '16':'0.03',
              '17':'0',
              '18':'0',
              '19':'0',
              '20':'0',
              '21':'0',
              '22':'0',
              '23':'0',
              '24':'0',
              '25':'0',
              '26':'0',
              '27':'0',
              '28':'0',
              '29':'0',
              '30':'0',
              '31':'0',
              '32':'0',
              '33':'0',
              '34':'0',
              '35':'0.03',
              '36':'0',
              '37':'0',
              '38':'0.03',
              '39':'0.03',
              '40':'0.03',
              '41':'0.03',
              '42':'0',
              '43':'0',
              '44':'0',
              '45':'0',
              '46':'0',
              '47':'0',
              '48':'0',
              '49':'0',
              '50':'0',
              '51':'0',
              '52':'0',
              '53':'0',
              '54':'0',
              '55':'0',
              '56':'0',
              '57':'0',
              '58':'0',
              '59':'0',
              '60':'0',
              '61':'0',
              '62':'0',
              '63':'0',
              '64':'0',
              '65':'0',
              '66':'0',
              '67':'0.03',
              '68':'0',
              '69':'0',
              '70':'0',
              '71':'0',
              '72':'0',
              '73':'0',
              '74':'0',
              '75':'0',
              '76':'0',
              '77':'0',
              '78':'0',
              '79':'0',
              '80':'0',
              '81':'0',
              '82':'0',
              '83':'0',
              '84':'0',
              '85':'0.03',
              '86':'0',
              '87':'0',
              '88':'0',
              '89':'0.03',
              '90':'0',
              '91':'0',
              '92':'0',
              '93':'0',
              '94':'0',
              '95':'0',
              '96':'0.03',
              '97':'0.03',
              '98':'0',
              '99':'0',
              '100':'0.03'}
print(type(Discount_dict))
Discount=pd.Series(Discount_dict)
Discount

<class 'dict'>

1         0
2         0
3         0
4         0
5         0
       ...
96     0.03
97     0.03
98        0
99        0
100    0.03
Length: 100, dtype: object

In [19]:
Sales_dict={'1':'6600',
              '2':'1500',
              '3':'6200',
              '4':'14000',
              '5':'2300',
              '6':'28000',
              '7':'3000',
              '8':'15000',
              '9':'6600',
              '10':'4250',
              '11':'19800',
              '12':'6800',
              '13':'27000',
              '14':'9000',
              '15':'5092.5',
              '16':'3201',
              '17':'9600',
              '18':'2400',
              '19':'2400',
              '20':'3000',
              '21':'1800',
              '22':'7000',
              '23':'53900',
              '24':'5000',
              '25':'7500',
              '26':'4200',
              '27':'4500',
              '28':'3850',
              '29':'2200',
              '30':'3600',
              '31':'2100',
              '32':'24000',
              '33':'15000',
              '34':'480',
              '35':'7566',
              '36':'9100',
              '37':'4500',
              '38':'38412',
              '39':'6111',
              '40':'33465',
              '41':'5820',
              '42':'800',
              '43':'7000',
              '44':'5000',
              '45':'2500',
              '46':'8200',
              '47':'8800',
              '48':'135000',
              '49':'900',
              '50':'8400',
              '51':'12000',
              '52':'6400',
              '53':'1900',
              '54':'31500',
              '55':'1750',
              '56':'2400',
              '57':'13500',
              '58':'8500',
              '59':'9600',
              '60':'8400',
              '61':'22000',
              '62':'3300',
              '63':'1800',
              '64':'11700',
              '65':'36000',
              '66':'9200',
              '67':'27645',
              '68':'60800',
              '69':'2000',
              '70':'1600',
              '71':'13200',
              '72':'6900',
              '73':'8800',
              '74':'6800',
              '75':'3000',
              '76':'1050',
              '77':'6000',
              '78':'12000',
              '79':'15000',
              '80':'2300',
              '81':'3300',
              '82':'5250',
              '83':'3300',
              '84':'3500',
              '85':'1746',
              '86':'3200',
              '87':'11500',
              '88':'7000',
              '89':'14938',
              '90':'1500',
              '91':'26000',
              '92':'2300',
              '93':'4600',
              '94':'37500',
              '95':'5500',
              '96':'3201',
              '97':'15617',
              '98':'1500',
              '99':'12000',
              '100':'12222'}
print(type(Sales_dict))
Sales=pd.Series(Sales_dict)
Sales

<class 'dict'>

1       6600
2       1500
3       6200
4      14000
5       2300
       ...
96      3201
97     15617
98      1500
99     12000
100    12222
Length: 100, dtype: object

In [21]:
Data=pd.DataFrame({'Order ID': Order_ID, 
                      'Order Date':Order_Date, 
                      'Customer ID':Customer_ID, 
                      'Segment':Segment, 
                      'Region':Region, 
                      'Category':Category,
                      'Product Name':Product_Name, 
                      'Price':Price, 
                      'Quantity':Quantity,
                      'Discount':Discount, 
                      'Sales':Sales})
Data

,Order ID,Order Date,Customer ID,Segment,Region,Category,Product Name,Price,Quantity,Discount,Sales
1,CA-2016-152156,2016.11.08,EB-13930,Хувь хүн,Баянзүрх,"Чихэр, печенье",Shokolinsen 250 гр,3300,2,0,6600
2,CA-2016-152156,2016.11.08,EB-13930,Хувь хүн,Баянзүрх,"OO ийн цаас, сальфетка",Хэрэглээ 00ийн цаас,500,3,0,1500
3,CA-2016-138688,2016.06.12,MO-17950,Байгууллага,Хан-Уул,"Чихэр, печенье",Алимтай жигнэмэг 230 гр,3100,2,0,6200
4,US-2015-108966,2015.10.11,JO-15550,Хувь хүн,Баянзүрх,Хиам бууз,Золотой янта 500 гр,2800,5,0,14000
5,US-2015-108966,2015.10.11,JO-15550,Хувь хүн,Баянзүрх,Ундаа ус,Punch 450 мл,1150,2,0,2300
...,...,...,...,...,...,...,...,...,...,...,...
96,US-2017-109484,2017.11.06,JR-15700,Гишүүн,Хан-Уул,"Компот варенье, хүүхдийн тэжээл",Hainich нухаш,3300,1,0.03,3201
97,CA-2017-161018,2017.11.09,AJ-10945,Гишүүн,Сүхбаатар,Самар чипс,Lays чипс 80 гр,2300,7,0.03,15617
98,CA-2017-157833,2017.06.17,BM-11575,Хувь хүн,Хан-Уул,"Набор, шоколад, бохь",Монстров 23 гр,500,3,0,1500
99,CA-2016-149223,2016.09.06,CV-12805,Байгууллага,Чингэлтэй,Архи пиво,Арвай 0.100,2000,6,0,12000
100,CA-2016-158568,2016.08.29,DK-12835,Гишүүн,Чингэлтэй,Бэлэн гоймон,Тэйсти гоймон 110 гр,1800,2,0.03,12222